Repository k-hackathon-bloom/bloom-backend, pull requests merged in 2024-09, with the labels that each got.

#2 프로젝트 초기 환경 구성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/test.adoc
  src/main/java/com/example/bloombackend/BloomBackendApplication.java
  src/main/java/com/example/bloombackend/restdocstest/controller/RestDocsTestController.java
  src/main/java/com/example/bloombackend/restdocstest/controller/dto/request/UserTestRequest.java
  src/main/java/com/example/bloombackend/restdocstest/controller/dto/response/UserTestResponse.java
  src/main/resources/application.properties
  src/main/resources/static/docs/test.html
  src/test/java/com/example/bloombackend/BloomBackendApplicationTests.java
  src/test/java/com/example/bloombackend/restdocs/RestDocsTest.java
Labels: enhancement

#4 feat: 카카오 소셜 로그인 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/example/bloombackend/oauth/OAuthProvider.java
  src/main/java/com/example/bloombackend/oauth/client/ClientConfig.java
  src/main/java/com/example/bloombackend/oauth/client/KaKaoApiClient.java
  src/main/java/com/example/bloombackend/oauth/controller/OAuthController.java
  src/main/java/com/example/bloombackend/oauth/controller/dto/request/KakaoLoginRequest.java
  src/main/java/com/example/bloombackend/oauth/controller/dto/response/KakaoInfoResponse.java
  src/main/java/com/example/bloombackend/oauth/service/OAuthLoginService.java
  src/main/java/com/example/bloombackend/oauth/service/RequestKakaoInfoService.java
  src/main/java/com/example/bloombackend/oauth/token/KakaoTokens.java
  src/main/java/com/example/bloombackend/restdocstest/controller/RestDocsTestController.java
  src/main/java/com/example/bloombackend/user/entity/Gender.java
  src/main/java/com/example/bloombackend/user/entity/UserEntity.java
  src/main/java/com/example/bloombackend/user/repository/UserRepository.java
  src/main/java/com/example/bloombackend/user/service/UserService.java
  src/main/resources/application.yml
Labels: enhancement

#12 fix: 로그인 api 수정
  src/main/java/com/example/bloombackend/oauth/controller/OAuthController.java
Labels: enhancement

#13 fix: api 요청 버그 수정
  src/main/java/com/example/bloombackend/oauth/controller/OAuthController.java
Labels: bug

#11 JWT AccessToken 인가 구현
  build.gradle
  src/main/java/com/example/bloombackend/global/config/JwtTokenProvider.java
  src/main/java/com/example/bloombackend/global/config/WebConfig.java
  src/main/java/com/example/bloombackend/global/config/annotation/CurrentUser.java
  src/main/java/com/example/bloombackend/global/config/resolver/CurrentUserResolver.java
  src/main/java/com/example/bloombackend/oauth/controller/OAuthController.java
  src/main/java/com/example/bloombackend/oauth/controller/dto/response/LoginResponse.java
  src/main/java/com/example/bloombackend/oauth/service/OAuthLoginService.java
Labels: enhancement

#14 퀘스트 도메인 개발
  src/docs/asciidoc/quest.adoc
  src/main/java/com/example/bloombackend/quest/controller/dto/QuestController.java
  src/main/java/com/example/bloombackend/quest/controller/dto/request/QuestRegisterRequest.java
  src/main/java/com/example/bloombackend/quest/controller/dto/response/AvailableQuestsResponse.java
  src/main/java/com/example/bloombackend/quest/controller/dto/response/QuestResponse.java
  src/main/java/com/example/bloombackend/quest/controller/dto/response/RegisteredQuestsResponse.java
  src/main/java/com/example/bloombackend/quest/controller/dto/response/UserQuestLogResponse.java
  src/main/java/com/example/bloombackend/quest/entity/QuestEntity.java
  src/main/java/com/example/bloombackend/quest/entity/UserQuestLogEntity.java
  src/main/java/com/example/bloombackend/quest/repository/QuestRepository.java
  src/main/java/com/example/bloombackend/quest/repository/UserQuestLogRepository.java
  src/main/java/com/example/bloombackend/quest/service/QuestService.java
  src/main/resources/static/docs/quest.html
  src/test/java/com/example/bloombackend/restdocs/QuestRestDocsTest.java
Labels: enhancement

#25 @Requestpart 사용시 application/octet-stream not supported 에러
  src/main/java/com/example/bloombackend/global/MultipartJackson2HttpMessageConverter.java
Labels: bug

#30 퀘스트 도메인 수정사항 반영
  build.gradle
  src/docs/asciidoc/quest.adoc
  src/main/java/com/example/bloombackend/global/config/QuerydslConfig.java
  src/main/java/com/example/bloombackend/quest/controller/dto/QuestController.java
  src/main/java/com/example/bloombackend/quest/repository/QuestRepository.java
  src/main/java/com/example/bloombackend/quest/repository/UserQuestLogRepository.java
  src/main/java/com/example/bloombackend/quest/repository/querydsl/QuestRepositoryCustom.java
  src/main/java/com/example/bloombackend/quest/repository/querydsl/QuestRepositoryImpl.java
  src/main/java/com/example/bloombackend/quest/repository/querydsl/UserQuestLogRepositoryCustom.java
  src/main/java/com/example/bloombackend/quest/repository/querydsl/UserQuestLogRepositoryImpl.java
  src/main/java/com/example/bloombackend/quest/service/QuestService.java
  src/main/resources/static/docs/quest.html
  src/test/java/com/example/bloombackend/restdocs/QuestRestDocsTest.java
Labels: bug, enhancement

#16 오늘의 질문 도메인 개발
  src/docs/asciidoc/daily-question.adoc
  src/main/java/com/example/bloombackend/dailyquestion/controller/DailyQuestionController.java
  src/main/java/com/example/bloombackend/dailyquestion/controller/request/DailyQuestionAnswerRequest.java
  src/main/java/com/example/bloombackend/dailyquestion/controller/response/DailyQuestionAnswerResponse.java
  src/main/java/com/example/bloombackend/dailyquestion/controller/response/DailyQuestionResponse.java
  src/main/java/com/example/bloombackend/dailyquestion/entity/DailyQuestionEntity.java
  src/main/java/com/example/bloombackend/dailyquestion/entity/DailyQuestionLogEntity.java
  src/main/java/com/example/bloombackend/dailyquestion/repository/DailyQuestionLogRepository.java
  src/main/java/com/example/bloombackend/dailyquestion/repository/DailyQuestionRepository.java
  src/main/java/com/example/bloombackend/dailyquestion/service/DailyQuestionService.java
  src/main/resources/static/docs/quest.html
  src/test/java/com/example/bloombackend/restdocs/DailyQuestionRestDocsTest.java
Labels: enhancement

#27 던리스트 도메인 수정사항 반영
  src/main/java/com/example/bloombackend/donelist/controller/dto/DoneListController.java
  src/main/java/com/example/bloombackend/donelist/controller/dto/request/CreateDoneItemRequest.java
  src/main/java/com/example/bloombackend/donelist/entity/DoneList.java
  src/main/java/com/example/bloombackend/donelist/repository/DoneListRepository.java
  src/main/java/com/example/bloombackend/donelist/service/DoneListService.java
Labels: enhancement

#22 던리스트 도메인 개발
  src/main/java/com/example/bloombackend/donelist/controller/dto/DoneListController.java
  src/main/java/com/example/bloombackend/donelist/controller/dto/request/CreateDoneItemRequest.java
  src/main/java/com/example/bloombackend/donelist/controller/dto/request/UpdateDoneItemRequest.java
  src/main/java/com/example/bloombackend/donelist/controller/dto/response/DoneItemDetailResponse.java
  src/main/java/com/example/bloombackend/donelist/controller/dto/response/DoneItemPhotoResponse.java
  src/main/java/com/example/bloombackend/donelist/controller/dto/response/DoneItemResponse.java
  src/main/java/com/example/bloombackend/donelist/controller/dto/response/DoneListResponse.java
  src/main/java/com/example/bloombackend/donelist/entity/DoneList.java
  src/main/java/com/example/bloombackend/donelist/entity/Photo.java
  src/main/java/com/example/bloombackend/donelist/repository/DoneListRepository.java
  src/main/java/com/example/bloombackend/donelist/repository/PhotoRepository.java
  src/main/java/com/example/bloombackend/donelist/service/DoneListService.java
  src/main/java/com/example/bloombackend/global/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/example/bloombackend/global/S3/S3Uploader.java
  src/main/java/com/example/bloombackend/global/config/S3Config.java
  src/main/resources/application.yml
Labels: enhancement

#35 보낸 메시지가 조회되지 않는 이슈 해결
  src/main/java/com/example/bloombackend/bottlemsg/repository/BottleMessageLogRepository.java
  src/main/java/com/example/bloombackend/bottlemsg/repository/BottleMessageReactionRepository.java
  src/main/java/com/example/bloombackend/bottlemsg/repository/BottleMessageRepository.java
  src/main/java/com/example/bloombackend/bottlemsg/sevice/BottleMessageService.java
Labels: bug

#43 유리병 메시지 도메인 리팩토링
  .gitignore
  src/docs/asciidoc/bottleMessageTest.adoc
  src/docs/asciidoc/bottleMessageTest.html
  src/main/generated/com/example/bloombackend/bottlemsg/entity/QBottleMessageEntity.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/BottleMessageController.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/BottleMessageDetailResponse.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/BottleMessageLogResponse.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/BottleMessageWithDateLogResponse.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/BottleMessageWithReactionResponse.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/Info/BottleMessageInfo.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/Info/BottleMessageLogInfo.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/Info/BottleMessageSummaryInfo.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/Info/BottleMessageWithDateLogInfo.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/Info/SentBottleMessageInfo.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/ReceivedBottleMessagesResponse.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/RecentSentAtResponse.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/SentBottleMessageResponse.java
  src/main/java/com/example/bloombackend/bottlemsg/controller/dto/response/UserBottleMessagesResponse.java
  src/main/java/com/example/bloombackend/bottlemsg/entity/BottleMessageEntity.java
  src/main/java/com/example/bloombackend/bottlemsg/entity/Negativity.java
  src/main/java/com/example/bloombackend/bottlemsg/repository/BottleMessageReactionRepository.java
  src/main/java/com/example/bloombackend/bottlemsg/repository/BottleMessageRepository.java
  src/main/java/com/example/bloombackend/bottlemsg/repository/querydsl/BottleMessageRepositoryImpl.java
  src/main/java/com/example/bloombackend/bottlemsg/sevice/AnalyzeMessagePrompt.java
  src/main/java/com/example/bloombackend/bottlemsg/sevice/BottleMessageService.java
  src/main/java/com/example/bloombackend/bottlemsg/sevice/ReactionService.java
  src/main/java/com/example/bloombackend/claude/service/ClaudeService.java
  src/test/java/com/example/bloombackend/restdocs/BottleMessageRestDocsTest.java
Labels: documentation, duplicate, enhancement
